### PR TITLE
Overhaul strings

### PR DESCRIPTION
**Pull request by MSF-Jarvis**
Updated most of the english on the front page. Let me know if you want me to proof-read the rest of the website as well.

P.S. I'll delete my fork as soon as this pull request gets merged/closed

### CODE REVIEW

**Comment by FireLord1** [comment]
thank you for showing interest here. you can commit and change things. leave my readme.md i added due to some reasons.. people downloaded my site as zip and used it without my permission so.. 

you can modify the site :dancer:

**Comment by MSF-Jarvis** [comment]
I know why you added the README Aman, that's why I mentioned the deletion of my fork. I'll review the repository again in the near future and see if there's something to be done :)

**Comment by thewisenerd** [comment]
while you're at it, you may as well fix the ```&```.

**Comment by MSF-Jarvis** [comment]
@thewisenerd, which & ?

No tilde on Sense keyboard, WTF

**Comment by FireLord1** [comment]
o.O

**Comment by thewisenerd** [comment]
@MSF-Jarvis ```&amp;``` not ```&```.

**Pull request merged**
